kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32000  # NodePort exposed by Argo CD service
        hostPort: 32000       # Port accessible on your VM's public IP
        protocol: TCP
